### ISSUE TITLE
Fetch commands don't have a nice error if the application isn't started

### ISSUE THREAD

**Issue by Teifion** [iacobson/ecspanse#23]
Obviously if the ` use Ecspanse` module isn't started as part of the supervision tree you get something like this:
```elixir
iex(2)> Durandal.Entities.Player.fetch()
** (ArgumentError) argument error
    (stdlib 5.2) :ets.select(:ets_ecspanse_components_state, [{{{:"$1", :"$2"}, :"$3", :"$4"}, [], [{{:"$1", :"$2"}}]}])
    (ecspanse 0.8.0) lib/ecspanse/util.ex:63: Ecspanse.Util.__list_entities_components_memoize/0
    (memoize 1.4.2) lib/memoize/cache.ex:111: Memoize.Cache.do_get_or_run/3
    (ecspanse 0.8.0) lib/ecspanse/query.ex:1002: Ecspanse.Query.filter_for_entities/1
    (ecspanse 0.8.0) lib/ecspanse/query.ex:214: Ecspanse.Query.stream/1
    (ecspanse 0.8.0) lib/ecspanse/query.ex:237: Ecspanse.Query.one/1
    (durandal 0.1.0) lib/durandal/entities/player.ex:16: Durandal.Entities.Player.fetch/0
    iex:2: (file)
```

For people brand new to the project who maybe missed that line at the start a more informative error message would be a nice pointer.

For context, the fetch command is from the tutorial (swap Hero for Player)
```elixir
  def fetch do
    Ecspanse.Query.select({Ecspanse.Entity}, with: [Components.Owner])
    |> Ecspanse.Query.one()
    |> case do
      {%Ecspanse.Entity{} = entity} -> {:ok, entity}
      _ -> {:error, :not_found}
    end
  end
  ```

**Comment by iacobson** [comment]
Thanks for the feedback. I will try to see if I can generically implement a meaningful error, for all query functions.
